# Generated by Django 3.2.4 on 2022-07-11 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('slug', models.SlugField()),
                ('co_authors', models.CharField(default=None, help_text='enter coauthors seperated by commas', max_length=300)),
                ('pub_date', models.DateField(blank=True, default=None)),
                ('volume', models.IntegerField(default=0)),
                ('pages', models.CharField(blank=True, help_text='must be in form nn--nn', max_length=50)),
                ('description', models.TextField(default='No description')),
                ('publisher', models.CharField(default=None, max_length=100)),
                ('general_ID', models.CharField(default='', max_length=100)),
                ('conference_name', models.CharField(blank=True, max_length=200, null=True)),
                ('conference_link', models.URLField(blank=True)),
                ('DOI', models.CharField(blank=True, max_length=100)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='generalArticle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('slug', models.SlugField()),
                ('co_authors', models.CharField(default=None, help_text='enter coauthors seperated by commas', max_length=300)),
                ('pub_date', models.DateField(blank=True, default=None)),
                ('volume', models.IntegerField(default=0)),
                ('pages', models.CharField(blank=True, help_text='must be in form nn--nn', max_length=50)),
                ('description', models.TextField(default='No description')),
                ('publisher', models.CharField(default=None, max_length=100)),
                ('conference_ID', models.CharField(default='', max_length=100)),
                ('conference_name', models.CharField(blank=True, max_length=200, null=True)),
                ('conference_link', models.URLField(blank=True)),
                ('DOI', models.CharField(blank=True, max_length=100)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='conferenceArticle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('slug', models.SlugField()),
                ('pub_date', models.DateField(blank=True, default=None)),
                ('description', models.TextField(default='No description')),
                ('co_authors', models.CharField(default=None, help_text='enter coauthors seperated by commas', max_length=200)),
                ('book_ID', models.CharField(default='', max_length=100)),
                ('pages', models.CharField(blank=True, help_text='must be in form nn--nn', max_length=50)),
                ('edition', models.CharField(blank=True, max_length=50, null=True)),
                ('isbn', models.CharField(blank=True, max_length=50, null=True)),
                ('chapters', models.CharField(blank=True, max_length=50, null=True)),
                ('book_link', models.URLField(blank=True)),
                ('DOI', models.CharField(blank=True, max_length=100)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('co_authors', models.CharField(default=None, help_text='enter coauthors seperated by and', max_length=300)),
                ('pub_date', models.DateField(blank=True, default=None)),
                ('journal', models.CharField(blank=True, max_length=100)),
                ('volume', models.IntegerField(default=0)),
                ('issue', models.IntegerField(default=0)),
                ('pages', models.CharField(blank=True, help_text='must be in form nn--nn', max_length=50)),
                ('description', models.TextField(default='No description')),
                ('publisher', models.CharField(default=None, max_length=100)),
                ('article_link', models.URLField(blank=True)),
                ('DOI', models.CharField(blank=True, max_length=100)),
                ('journal_ID', models.CharField(default='', max_length=100)),
                ('journal_type', models.CharField(choices=[('National', 'National'), ('International', 'International')], default='National', max_length=20)),
                ('impactFactor', models.FloatField(default=0)),
                ('sjrRating', models.FloatField(default=0)),
                ('quartile', models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=5)),
                ('peer_reviewed', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='journals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
