# Generated by Django 3.2.4 on 2022-07-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220711_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='version',
            field=models.FloatField(default=1.0),
        ),
    ]
