# Generated by Django 3.2.4 on 2022-07-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AlterField(
            model_name='article',
            name='journal_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
