# Generated by Django 3.2.4 on 2022-07-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='version',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='conferencearticle',
            name='version',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='generalarticle',
            name='version',
            field=models.FloatField(default=1.0),
        ),
    ]
